# Site settings
title: MattOps
email: matt@mattops.io
description: "Development. Administration. Automation. Security."
baseurl: ""
url: https://mattops.io

author:
  name: 'Matt Spaulding'
  email: matt@mattops.io
  url: https://mattops.io

github: https://github.com/mspaulding06/
disqus_shortname: mattops-blog
google_analytics: UA-89475997-1

links:
  haskell: https://www.meetup.com/Beaverton-Haskell-Meetup/
  keybase: https://keybase.io/mattops/

plugins: [jekyll-paginate]

paginate: 5
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/

exclude:
  - README.md
  - LICENSE
  - Rakefile
  - Gemfile
  - Gemfile.lock
